# Generated by Django 4.1.3 on 2022-11-08 01:42

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16)),
                ('Mfgdate', models.CharField(max_length=4)),
                ('Url', models.CharField(max_length=100)),
                ('Graphic', models.ImageField(upload_to='cpu_images')),
                ('Score', models.CharField(max_length=4)),
                ('String', models.CharField(max_length=16)),
                ('Fullstring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=32)),
                ('First_name', models.CharField(max_length=32)),
                ('Last_name', models.CharField(max_length=32)),
                ('Entry_date', models.DateTimeField(auto_now=True)),
                ('Work_email', models.CharField(max_length=500)),
                ('Personal_email', models.CharField(max_length=500)),
                ('Work_phone', models.CharField(max_length=14)),
                ('Extension', models.PositiveSmallIntegerField()),
                ('Home_phone', models.CharField(default='unknown', max_length=14)),
                ('Street', models.CharField(max_length=32)),
                ('City', models.CharField(max_length=32)),
                ('State', models.CharField(default='TX', max_length=32)),
                ('Country', models.CharField(default='USA', max_length=32)),
                ('Hire_date', models.DateTimeField()),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('Picture', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='employee_pictures', verbose_name='Picture')),
                ('Remote', models.BooleanField(default=True)),
                ('Active', models.BooleanField(default=True)),
                ('Pic_time_stamp', models.DateTimeField(blank=True, null=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.department')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host_name', models.CharField(max_length=32)),
                ('Uuid', models.UUIDField(db_index=True)),
                ('Ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('External_ipaddress', models.CharField(blank=True, max_length=15, null=True)),
                ('Dns_address', models.CharField(blank=True, max_length=50, null=True)),
                ('Ram', models.SmallIntegerField(blank=True, null=True)),
                ('OS_info', models.CharField(blank=True, max_length=100, null=True)),
                ('System_info', models.TextField(blank=True, null=True)),
                ('Drive', models.TextField(blank=True, null=True)),
                ('Monitor', models.TextField(blank=True, null=True)),
                ('Isp', models.CharField(blank=True, max_length=100, null=True)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('Check_in', models.DateTimeField(auto_now=True)),
                ('Cpufullstring', models.CharField(blank=True, max_length=100, null=True)),
                ('Laptop', models.BooleanField(blank=True, null=True)),
                ('Local_admin_password', models.CharField(blank=True, max_length=20, null=True)),
                ('Local_encryption_password_key', models.CharField(blank=True, max_length=100, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('vpnkey', models.CharField(blank=True, max_length=20, null=True)),
                ('Handoff_date', models.DateTimeField(blank=True, null=True)),
                ('Export_to_api', models.BooleanField(default=True)),
                ('Export_to_windows_api', models.BooleanField(default=False)),
                ('Enable_alerts', models.BooleanField(default=True)),
                ('Encryption_password_enforcement', models.BooleanField(default=True)),
                ('Cpu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.cpu_table')),
                ('User_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='System_change_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log', models.TextField()),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('System', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.system')),
            ],
        ),
    ]
