# Generated by Django 4.1.3 on 2022-11-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='System_update_status',
            field=models.BooleanField(default=False),
        ),
    ]
