# Generated by Django 4.1.3 on 2022-11-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djinventory', '0003_component_component_type_manufacturer_rma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='vpnkey',
            new_name='Vpn_key',
        ),
    ]
