# Generated by Django 4.1.3 on 2022-11-09 02:06

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('djinventory', '0004_rename_vpnkey_system_vpn_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Box', models.ImageField(blank=True, null=True, upload_to='purchases')),
                ('Reciept_picture', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='order_reciepts', verbose_name='Reciept')),
                ('Box_picture', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='order_boxes', verbose_name='Box')),
                ('Amount', models.PositiveSmallIntegerField()),
                ('Entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djinventory.vendor')),
            ],
        ),
    ]
