# Generated by Django 4.1.3 on 2022-11-09 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('djinventory', '0006_site_employee_site_system_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active', models.BooleanField(default=True)),
                ('Serial_number', models.CharField(max_length=100, unique=True)),
                ('Extra_information', models.TextField(blank=True, null=True)),
                ('Picture', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='assetpictures', verbose_name='assetpicture')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset', models.CharField(max_length=100, unique=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Closed_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Old_id', models.CharField(max_length=50)),
                ('Sla', models.BooleanField(default=True)),
                ('Problem', models.CharField(max_length=200)),
                ('Owner', models.CharField(max_length=15)),
                ('Ticket_creation', models.DateTimeField()),
                ('Closer', models.CharField(max_length=100)),
                ('Closed', models.DateTimeField(auto_now_add=True)),
                ('Minutes', models.IntegerField(default=0)),
                ('Update_count', models.IntegerField(default=0)),
                ('Minutes_open', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Decomissioned_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uuid', models.UUIDField(db_index=True)),
                ('System_information', models.TextField(blank=True, null=True)),
                ('Cpufullstring', models.CharField(blank=True, max_length=100, null=True)),
                ('Account', models.CharField(blank=True, max_length=100, null=True)),
                ('Decom_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sla', models.BooleanField(default=True)),
                ('Problem', models.CharField(max_length=200)),
                ('Email_user', models.BooleanField(default=False)),
                ('Email_managers', models.BooleanField(default=False)),
                ('Ticket_owner', models.CharField(max_length=15)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('Minutes', models.IntegerField(default=0)),
                ('Issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='system',
            old_name='System_info',
            new_name='System_information',
        ),
        migrations.CreateModel(
            name='Ticket_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Start', models.DateTimeField(default=django.utils.timezone.now)),
                ('Text', models.TextField()),
                ('Upload', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='opentickets', verbose_name='file')),
                ('Hidden', models.BooleanField(default=False)),
                ('Minutes', models.IntegerField(default=0)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('Ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='Ticket_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.ticket_status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.employee'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32)),
                ('Email_enable', models.BooleanField(default=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.department')),
            ],
        ),
        migrations.CreateModel(
            name='Decomissioned_component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial_number', models.CharField(max_length=100)),
                ('Account', models.CharField(blank=True, max_length=100, null=True)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('Part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.component')),
                ('Purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.purchase')),
                ('Rma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.rma')),
            ],
        ),
        migrations.CreateModel(
            name='Closed_ticket_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Added', models.DateTimeField(auto_now_add=True)),
                ('Text', models.TextField()),
                ('Upload', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='opentickets', verbose_name='file')),
                ('Hidden', models.BooleanField(default=True)),
                ('Minutes', models.IntegerField(default=0)),
                ('Ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.closed_ticket')),
            ],
        ),
        migrations.AddField(
            model_name='closed_ticket',
            name='Issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.issue'),
        ),
        migrations.AddField(
            model_name='closed_ticket',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.employee'),
        ),
        migrations.CreateModel(
            name='Assetlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log', models.TextField()),
                ('Time_stamp', models.DateTimeField(auto_now_add=True)),
                ('User_stamp', models.TextField()),
                ('Asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djinventory.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='Asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.asset_type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djinventory.manufacturer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='PartNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.component'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.purchase'),
        ),
        migrations.AddField(
            model_name='asset',
            name='RMA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.rma'),
        ),
        migrations.AddField(
            model_name='asset',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.employee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.system'),
        ),
    ]
