# Generated by Django 4.1.3 on 2022-11-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djinventory', '0007_asset_asset_type_closed_ticket_decomissioned_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='PartNumber',
        ),
        migrations.AddField(
            model_name='asset',
            name='Component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.component_list'),
        ),
        migrations.AddField(
            model_name='component',
            name='Purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djinventory.purchase'),
        ),
    ]
